/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ErrorBlock: typeof import('./src/components/ui/ErrorBlock.vue')['default']
    FavouriteButton: typeof import('./src/components/ui/FavouriteButton.vue')['default']
    PokedexExplorer: typeof import('./src/components/PokedexExplorer/PokedexExplorer.vue')['default']
    PokedexExplorerFilters: typeof import('./src/components/PokedexExplorer/PokedexExplorerFilters.vue')['default']
    PokedexExplorerItem: typeof import('./src/components/PokedexExplorer/PokedexExplorerItem.vue')['default']
    PokedexExplorerSearch: typeof import('./src/components/PokedexExplorer/PokedexExplorerSearch.vue')['default']
    PokedexExplorerTabs: typeof import('./src/components/PokedexExplorer/PokedexExplorerTabs.vue')['default']
    PokemonDetailsPage: typeof import('./src/components/PokemonDetailsPage/PokemonDetailsPage.vue')['default']
    PokemonDetailsPageDetails: typeof import('./src/components/PokemonDetailsPage/PokemonDetailsPageDetails.vue')['default']
    PokemonDetailsPageHead: typeof import('./src/components/PokemonDetailsPage/PokemonDetailsPageHead.vue')['default']
    PokemonDetailsPageNotFound: typeof import('./src/components/PokemonDetailsPage/PokemonDetailsPageNotFound.vue')['default']
    PokemonDetailsPageStatsTable: typeof import('./src/components/PokemonDetailsPage/PokemonDetailsPageStatsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
